const state = {
  userData: {
    areaId: '1'
  },
  cityAreaId: '',
  factoryAreaId: '',
  buildingAreaId: '',
  floorPlansAreaId: '',
  username: '',
  usericon: '',
  userToken: '',
  loading: false,
  maintainProject: window.localStorage.pattern ? window.localStorage.pattern : '',
  clientId: `${Math.random() * 8000 + 1000}${new Date().getTime()}`,
  userList: [],
  treeStructure: [],
  cityDataDelete: false,
  cityData: {},
  cityDataMq: {},
  factoryDataDelete: false,
  factoryData: {},
  factoryDataMq: {},
  buildingDataDelete: false,
  buildingData: {},
  buildingDataMq: {},
  floorDataDelete: false,
  floorData: {},
  floorDataMq: {},
  mapLoadingState1: false,
  mapLoadingState2: false,
  mapLoadingState3: false,
  mapLoadingState4: false,
  mapLoadingStateMq: false,
  firstList: [],
  allList: [],
  alarmMq: {},
  alarmId: '',
  repairId: ''
}

export default state
